sudo: false

language: java

script: mvn clean package -f hestia-parent/pom.xml

jdk: oraclejdk7

after_success:
  - echo "<settings><servers><server><id>nexus-snapshots</id><username>\${env.CI_DEPLOY_USERNAME}</username><password>\${env.CI_DEPLOY_PASSWORD}</password></server></servers></settings>"
  > ~/settings.xml
  - if [ -z ${TRAVIS_TAG} ]; then mvn deploy -f hestia-parent/pom.xml -DskipTests --settings
  ~/settings.xml; fi

before_deploy:
  - mvn package
  - zip -r ${TRAVIS_TAG}.zip target/*.jar

deploy:
  provider: releases
  api_key:
    secure: XyLxQcS14znfXS6Lylf2YrPkqpCOi13xHLLGB0yhGn5uoqfzbel0gvD/5mhCz12yOnsGZSJIP91WkJM6enjgto+FPYP994Pjvuuqn2hrMFqPDpEcdclB5es6TvJQd2wPj4FzkiBxEeootujF8I7jiMCoLJSl9Xp4peQbsM8s/jo=
  file: "${TRAVIS_TAG}.zip"
  on:
    repo: ressec/hestia
    tags: true
    all_branches: true

notifications:
  slack:
    rooms:
      - heliosphere-team:Bja0bgXlnUECFqYeffLcSzvX#travis
      
